sudo: 'required'

language: 'node_js'
node_js:
  - 'node'
  - '8'

services:
  - 'docker'

cache:
  directories:
    - 'node_modules'

install:
  - 'npm install'
  - 'npm run build'

script:
  - 'npm run test'

deploy:
  - provider: 'npm'
    email: '$NPM_EMAIL'
    api_key:
      secure: '$NPM_API_KEY'
    skip_cleanup: true
    on:
      branch: 'master'
      node: '8'
      tags: true
  - provider: 'script'
    script: './docker-deploy.sh'
    skip_cleanup: true
    on:
      branch: 'master'
      node: '8'
      tags: true
