sudo: 'required'

language: 'node_js'
node_js:
  - 'node'
  - '8'

addons:
  sonarcloud:
    organization: 'kobionic'

services:
  - 'docker'

cache:
  directories:
    - 'node_modules'

install:
  - 'npm install'
  - 'npm run build'

script:
  - 'npm run test'
  - 'docker-compose build'
  - 'sh sonar.sh'

deploy:
  provider: 'npm'
  email: '$NPM_EMAIL'
  api_key:
    secure: '$NPM_API_KEY'
  skip_cleanup: true
  on:
    branch: 'master'
    node: '8'
    tags: true
