version: '3'

services:
  ncs:
    build: .
    image: 'kobionic/node-config-server'
    container_name: 'ncs'
    restart: 'always'
    ports:
      - '20490:20490'
    volumes:
      - './config:/home/node/config:rw'
      - './ncs.config.json:/home/node/ncs.config.json:ro'
